root = "."
tmp_dir = "air"

[build]
  cmd = "go build -o ./bin/ncore-tmdb ./cmd/run/"
  bin = "bin/ncore-tmdb"
  full_bin = "APP_ENV=dev APP_USER=air ./bin/ncore-tmdb"
  include_ext = ["go", "tpl", "tmpl", "html", "widget"]
  exclude_dir = ["assets", "tmp", "vendor", "dashboard", "bin"]
  delay = 1000
  stop_on_error = true
  kill_delay = "500ms"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
