replicaCount: 1

tmdb:
  image:
    repository: imdonix/ncore-tmdb
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  env:
    ncoreHost: "http://ncore:8080"
    qbitHost: "http://qbittorrent:8080"
    existingSecret: "ncore-tmdb-secrets"

ncore:
  enabled: true
  image:
    repository: imdonix/ncore
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
