apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ncore-tmdb.fullname" . }}
  labels:
    {{- include "ncore-tmdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ncore-tmdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ncore-tmdb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ncore-tmdb
          image: "{{ .Values.ncoreTmdb.image.repository }}:{{ .Values.ncoreTmdb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ncoreTmdb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NCORE_HOST
              value: {{ .Values.ncoreTmdb.env.ncoreHost | quote }}
            - name: NCORE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ncoreTmdb.env.existingSecret }}
                  key: NCORE_USER
            - name: NCORE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ncoreTmdb.env.existingSecret }}
                  key: NCORE_PASS
            - name: QBIT_HOST
              value: {{ .Values.ncoreTmdb.env.qbitHost | quote }}
            - name: QBIT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ncoreTmdb.env.existingSecret }}
                  key: QBIT_USER
            - name: QBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ncoreTmdb.env.existingSecret }}
                  key: QBIT_PASS
            - name: TMDB_API_KEY
              value: {{ .Values.ncoreTmdb.env.tmdbApiKey | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ncore-tmdb.fullname" . }}
  labels:
    {{- include "ncore-tmdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ncoreTmdb.service.type }}
  ports:
    - port: {{ .Values.ncoreTmdb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ncore-tmdb.selectorLabels" . | nindent 4 }}
